[package]
name = "filestatx"
version = "1.0.0"
authors = []
edition = "2021"

[lib]
name = "filestatx"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.36.2"

[features]
nif_version_2_15 = ["rustler/nif_version_2_15"]
nif_version_2_16 = ["rustler/nif_version_2_16"]
